language: php

cache:
  directories:
  - vendor

php:
  - 5.6
  - 5.5
  - 5.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - alias composer="php -d zend.enable_gc=0 /usr/bin/composer"
  - composer install

script:
  - bin/phpunit --coverage-text